### PR TITLE
fix(#324): expand generic types when inlining

### LINKED ISSUE #324: Type checking leaves fully determined types generic in generated code
The function
```
pub def even_primes:list(int) = [2]
```
generates the code
```
even_primes(?#result##0:wybe.list(wybe.int))<{}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm alloc(16:wybe.int, ?tmp#4##0:wybe.list(T)) @list:9:27
    foreign lpvm mutate(~tmp#4##0:wybe.list(T), ?tmp#5##0:wybe.list(T), 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 2:T) @list:9:27
    foreign lpvm mutate(~tmp#5##0:wybe.list(T), ?#result##0:wybe.list(wybe.int), 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 0:wybe.list(T)) @list:9:27
```
Note that the proc type is correct, but after that, all the `list(int)` types show up as `list(T)`.

### PR DESCRIPTION
**Pull request by jimbxb**
Closes #324

### CODE REVIEW

File: src/BodyBuilder.hs [hunk 1]
```diff
@@ -217,11 +217,17 @@ type ComputedCalls = Map Prim [PrimArg]
 -- |Allocate the next temp variable name and ensure it's not allocated again
 freshVarName :: BodyBuilder PrimVarName
 freshVarName = do
-    tmp <- gets tmpCount
+    tmp <- freshTmp
     logBuild $ "Generating fresh variable " ++ mkTempName tmp
```
Comment (pschachte) [inline src/BodyBuilder.hs]: I think it would be cleaner to call mkTempName in a let, so it isn't repeated.
