### PR TITLE
Corrected checking of flows in higher order calls

### LINKED ISSUE #318: Calling a higher-order proc with no output arguments generates invalid LLVM IR
Consider either of these two test functions:

```
def {impure} measure(func: {impure}(input: T, output: T2), input: T, ?output: T2) {
    !func(input, ?output)
}

def measure2(func: (input: T, output: T2), input: T, ?output: T2) {
    func(input, ?output)
}
```

It looks like codegen tries to assign the `void` result to a variable:

```
Blocks: define external fastcc  i64 @"crash_compiler.measure<0>"(i64  %"func##0", i64  %"input##0")    {
Blocks: entry:
Blocks:   %0 = inttoptr i64 %"func##0" to i64* 
Blocks:   %1 = load  i64, i64* %0 
Blocks:   %2 = inttoptr i64 %1 to void (i64, i64, i64)* 
Blocks:   %3 = tail call fastcc  void  %2(i64  %"func##0", i64  %"input##0")  
Blocks:   ret i64 %3 
Blocks: }
Blocks: 
Blocks: 
Blocks: define external fastcc  i64 @"crash_compiler.measure2<0>"(i64  %"func##0", i64  %"input##0")    {
Blocks: entry:
Blocks:   %0 = inttoptr i64 %"func##0" to i64* 
Blocks:   %1 = load  i64, i64* %0 
Blocks:   %2 = inttoptr i64 %1 to void (i64, i64, i64)* 
Blocks:   %3 = tail call fastcc  void  %2(i64  %"func##0", i64  %"input##0")  
Blocks:   ret i64 %3 
Blocks: }
Blocks: -----------------------------------------------------------------
Blocks: *** Exiting Module crash_compiler ***
EncodeException "Instruction of type void must not have a name: UnName 3 := Call {tailCallKind = Just Tail, callingConvention = Fast, returnAttributes = [], function = Right (LocalReference (PointerType {pointerReferent = FunctionType {resultType = VoidType, argumentTypes = [IntegerType {typeBits = 64},IntegerType {typeBits = 64},IntegerType {typeBits = 64}], isVarArg = False}, pointerAddrSpace = AddrSpace 0}) (UnName 2)), arguments = [(LocalReference (IntegerType {typeBits = 64}) (Name \"func##0\"),[]),(LocalReference (IntegerType {typeBits = 64}) (Name \"input##0\"),[])], functionAttributes = [], metadata = []}"
```

The same doesn't occur with a normal first-order call, e.g.:

```
def {impure, noinline} foo(x: int, y: int) {
    ?x2 = x
}

!foo(2, 3)
```

### PR DESCRIPTION
**Pull request by jimbxb**
Fixes #318

### CODE REVIEW

File: src/Types.hs [hunk 1]
```diff
@@ -383,8 +385,13 @@ typeErrorMessage (ReasonExpType exp ty pos) =
         "Type of " ++ show exp ++ " incompatible with " ++ show ty
 typeErrorMessage (ReasonHigher callFrom callTo pos) =
     Message Error pos $
-        "Higher order call to " ++ show callTo ++ " in "
+        "Higher order call to " ++ showProcName callTo ++ " in "
         ++ showProcName callFrom ++ " has a type/flow error."
+typeErrorMessage (ReasonHigherFlow callFrom callTo idx pos) =
+    Message Error pos $
+        "Higher order call to " ++ showProcName callTo ++ " in "
+        ++ showProcName callFrom ++ " has a flow error in argument "
```
Comment (pschachte) [inline src/Types.hs:393]: Can you give more helpful information, like which argument(s) have the wrong flow, what the expected flow is, and what the actual flow is?

**Review by pschachte — APPROVED** [review]
Perfect, thanks, James.
